name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: npm run download-binaries

      - name: Build
        run: npm run build

      - name: Upload artifact (Linux, x64)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (Linux, x64)
          path: ./dist/linux-x64

      - name: Upload artifact (Linux, arm64)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (Linux, arm64)
          path: ./dist/linux-arm64

      - name: Upload artifact (Windows, x64)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (Windows, x64)
          path: ./dist/windows-x64

      - name: Upload artifact (macOS, x64)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (macOS, x64)
          path: ./dist/macos-x64

      - name: Upload artifact (macOS, arm64)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (macOS, arm64)
          path: ./dist/macos-arm64

      - name: Upload artifact (All)
        uses: actions/upload-artifact@v5
        with:
          name: Tidalwave (All)
          path: |
            ./dist/tidalwave-linux-x64.tar.gz
            ./dist/tidalwave-linux-arm64.tar.gz
            ./dist/tidalwave-windows-x64.zip
            ./dist/tidalwave-macos-x64.zip
            ./dist/tidalwave-macos-arm64.zip